name: simple_dart_theme_controller
description: Theme Controller for Simple Dart UI framework
version: 0.0.1
repository: https://github.com/simple-dart/theme_controller
platforms:
  web:

environment:
  sdk: '>=2.18.0 <3.0.0'



dev_dependencies:
  build_runner: ^2.3.2
  build_web_compilers:
